name: Lint

on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    env:
      TF_WORKSPACE: prd
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    -
      name: Terraform Format
      id: fmt
      run: terraform fmt -check -diff
