version: "3.9"
services:
  web:
    build:
      context: ./frontend
      args:
        ENV: 'dev'
    ports:
      - "8000:80"
  api:
    build:
      context: ./backend
      args:
        ENV: 'dev'
    ports:
      - "8000:80"